### ISSUE TITLE
events.js:184 Unhandled 'error' event

### ISSUE THREAD

**Issue by Kallagan93** [aubguillemette/discord2slack#8]
events.js:184
    throw err; // Unhandled 'error' event
    ^

Error [ERR_UNHANDLED_ERROR]: Unhandled error. (ErrorEvent {
  target:
   WebSocket {
     _events:
      [Object: null prototype] {
        message: [Function],
        open: [Function],
        error: [Function],
        close: [Function] },
     _eventsCount: 4,
     _maxListeners: undefined,
     readyState: 2,
     protocol: '',
     _binaryType: 'nodebuffer',
     _finalize: [Function: bound finalize],
     _closeFrameReceived: false,
     _closeFrameSent: false,
     _closeMessage: '',
     _closeTimer: null,
     _finalized: true,
     _closeCode: 1006,
     _extensions: {},
     _isServer: false,
     _receiver:
      Receiver {
        _binaryType: 'nodebuffer',
        _extensions: null,
        _maxPayload: 0,
        _bufferedBytes: 0,
        _buffers: null,
        _compressed: false,
        _payloadLength: 406,
        _fragmented: 0,
        _masked: false,
        _fin: true,
        _mask: null,
        _opcode: 1,
        _totalPayloadLength: 0,
        _messageLength: 0,
        _fragments: null,
        _cleanupCallback: null,
        _isCleaningUp: false,
        _hadError: false,
        _loop: false,
        add: [Function: bound add],
        onmessage: null,
        onclose: null,
        onerror: null,
        onping: null,
        onpong: null,
        _state: 0 },
     _sender:
      Sender {
        _extensions: {},
        _socket: [TLSSocket],
        _firstFragment: true,
        _compress: false,
        _bufferedBytes: 0,
        _deflating: false,
        _queue: [] },
     _socket:
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: 'gateway.discord.gg',
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 5,
        connecting: false,
        _hadError: false,
        _parent: null,
        _host: 'gateway.discord.gg',
        _readableState: [ReadableState],
        readable: false,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: null,
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: null,
        timeout: 0,
        [Symbol(res)]: [TLSWrap],
        [Symbol(asyncId)]: 46753,
        [Symbol(kHandle)]: null,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBytesRead)]: 813749,
        [Symbol(kBytesWritten)]: 17101,
        [Symbol(connect-options)]: [Object] },
     _error: null,
     url: 'wss://gateway.discord.gg/?v=6&encoding=json',
     _req: null },
  type: 'error',
  message: 'read ECONNRESET',
  error:
   { Error: read ECONNRESET
       at TLSWrap.onStreamRead (internal/stream_base_commons.js:167:27) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' } })
    at Client.emit (events.js:182:17)
    at WebSocketConnection.onError (/home/pi/SlackDiscordBridges/itemboerse/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:374:17)
    at WebSocket.onError (/home/pi/SlackDiscordBridges/itemboerse/node_modules/ws/lib/event-target.js:128:16)
    at WebSocket.emit (events.js:193:13)
    at _receiver.cleanup (/home/pi/SlackDiscordBridges/itemboerse/node_modules/ws/lib/websocket.js:211:14)
    at Receiver.cleanup (/home/pi/SlackDiscordBridges/itemboerse/node_modules/ws/lib/receiver.js:557:13)
    at WebSocket.finalize (/home/pi/SlackDiscordBridges/itemboerse/node_modules/ws/lib/websocket.js:206:20)
    at TLSSocket.emit (events.js:193:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! discord2slack@0.0.3 start: `node discord2slack.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the discord2slack@0.0.3 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by aubguillemette** [comment]
Hi, can you specify your npm + node version? Also, can you describe how to reproduce the issue?
